name: TMPNN
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - alabaster=0.7.12
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - astroid=2.14.2
  - asttokens=2.0.5
  - atomicwrites=1.4.0
  - attrs=22.1.0
  - autopep8=1.6.0
  - babel=2.11.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.2
  - binaryornot=0.4.4
  - black=23.3.0
  - blas=1.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.15.1
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cookiecutter=1.7.3
  - cryptography=39.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.6
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - entrypoints=0.4
  - executing=0.8.3
  - filelock=3.9.0
  - flake8=6.0.0
  - fonttools=4.25.0
  - freetype=2.10.4
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - inflection=0.5.1
  - intel-openmp=2023.1.0
  - intervaltree=3.1.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jaraco.classes=3.2.1
  - jedi=0.18.1
  - jellyfish=0.9.0
  - jinja2=3.1.2
  - jinja2-time=0.2.0
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - keyring=23.13.1
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lazy-object-proxy=1.6.0
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.39
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libtiff=4.5.0
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mistune=0.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - more-itertools=8.12.0
  - mpmath=1.2.1
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbclassic=1.0.0
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - numpy=1.24.3
  - numpy-base=1.24.3
  - numpydoc=1.5.0
  - openssl=1.1.1w
  - packaging=23.0
  - pandocfilters=1.5.0
  - paramiko=2.8.1
  - parso=0.8.3
  - pathspec=0.10.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.4.0
  - poyo=0.5.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.0.1
  - pygments=2.15.1
  - pylint=2.16.2
  - pylint-venv=2.3.0
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyqtwebengine=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-lsp-black=1.2.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.7.2
  - python-slugify=5.0.2
  - python_abi=3.8
  - pytoolconfig=1.2.5
  - pytorch=2.0.1
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pywin32=305
  - pywin32-ctypes=0.2.0
  - pywinpty=2.0.10
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qdarkstyle=3.0.2
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.2.2
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - requests=2.29.0
  - rope=1.7.0
  - rtree=1.0.1
  - scipy=1.10.1
  - send2trash=1.8.2
  - setuptools=66.0.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.4
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.4.3
  - spyder-kernels=2.4.3
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - terminado=0.17.1
  - text-unidecode=1.3
  - textdistance=4.2.1
  - three-merge=0.1.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - ujson=5.4.0
  - unidecode=1.2.0
  - urllib3=1.26.15
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - whatthepatch=1.0.2
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.14.1
  - xz=5.4.2
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
